package extractor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Kong/kuma-migrator/pkg/config"
	"github.com/Kong/kuma-migrator/pkg/resource"
	"github.com/Kong/kuma-migrator/pkg/ui"
	"sigs.k8s.io/yaml"
)

// loadSkipSet loads the user config and returns the skip set. On error it logs
// a warning and falls back to an empty set (no additional skipping).
func loadSkipSet() map[string]bool {
	cfg, err := config.Load()
	if err != nil {
		fmt.Printf("  [WARN] could not load config (skip list ignored): %v\n", err)
		return map[string]bool{}
	}
	return cfg.SkipSet()
}

// gatewayLocalKinds is the set of resource types that may be created directly on a Zone
// or Standalone CP and therefore may NOT carry a kuma.io/origin: zone label.
//
// Two categories:
//
//  1. Strictly zone-local (never synced to Global CP):
//     MeshGatewayInstance, MeshGatewayConfig — these are always zone-created and have no
//     origin label.
//
//  2. Gateway policy kinds that can be created on either the Global CP or the Zone CP:
//     MeshGateway, MeshHTTPRoute, MeshTCPRoute, MeshGatewayRoute — when created on the
//     Global CP they are synced to zones WITH kuma.io/origin: global (skipped by the normal
//     origin filter). When created directly on the Zone CP they carry no origin label and
//     must be kept.
//
// On a Zone CP extraction these kinds are kept when the origin label is absent;
// resources explicitly labelled kuma.io/origin: global are still skipped.
var gatewayLocalKinds = map[string]bool{
	"MeshGatewayInstance": true,
	"MeshGatewayConfig":   true,
	"MeshGateway":         true,
	"MeshHTTPRoute":       true,
	"MeshTCPRoute":        true,
	"MeshGatewayRoute":    true,
}

// zoneOnlyKinds is the set of resource types that must be extracted from Zone or
// Standalone CPs only. They are skipped during Global CP extraction.
//
//   - MeshGatewayInstance: zone-local; never synced to the Global CP.
//   - MeshGatewayConfig: zone-local companion to MeshGatewayInstance; never synced to Global.
var zoneOnlyKinds = map[string]bool{
	"MeshGatewayInstance": true,
	"MeshGatewayConfig":   true,
}

// isGatewayLocalKind reports whether kind is a gateway resource that may lack
// kuma.io/origin labels on a Zone CP (see gatewayLocalKinds).
func isGatewayLocalKind(kind string) bool {
	return gatewayLocalKinds[kind]
}

// isZoneOnlyKind reports whether kind must be extracted from Zone/Standalone CPs only
// and should be skipped during Global CP extraction (see zoneOnlyKinds).
func isZoneOnlyKind(kind string) bool {
	return zoneOnlyKinds[kind]
}

// writeResourceFiles splits a multi-document YAML stream into individual files under outputDir.
// Documents whose kind contains "Insight" or is in skipSet are silently skipped.
// On a Zone CP (cpMode == CPModeZone) only resources with kuma.io/origin: zone are kept,
// with the exception of gateway-local kinds which may lack the label (see gatewayLocalKinds).
// Files are written into per-kind subfolders (resiliency/, routing/, etc.).
// Returns the number of files written.
func writeResourceFiles(data []byte, outputDir string, skipSet map[string]bool, cpMode string) (int, error) {
	docs := splitYAMLDocs(data)
	count := 0
	for _, doc := range docs {
		doc = strings.TrimSpace(doc)
		if doc == "" {
			continue
		}

		var obj map[string]interface{}
		if err := yaml.Unmarshal([]byte(doc), &obj); err != nil || obj == nil {
			continue
		}

		kind, _ := obj["kind"].(string)
		if kind == "" {
			continue
		}
		if isInsightKind(kind) || skipSet[kind] {
			continue
		}

		meta, _ := obj["metadata"].(map[string]interface{})
		name, _ := meta["name"].(string)
		ns, _ := meta["namespace"].(string)
		labels, _ := meta["labels"].(map[string]interface{})

		// Skip MeshService CRs that were auto-generated by Kuma from Kubernetes Services.
		// These carry kuma.io/env: kubernetes and do not need to be extracted or re-applied.
		if kind == "MeshService" {
			if env, _ := labels["kuma.io/env"].(string); env == "kubernetes" {
				continue
			}
		}

		// On a Global CP, skip zone-only kinds (MeshGateway, MeshGatewayInstance, etc.).
		// They may appear on the global CP via KDS sync but must be extracted from zone CPs.
		if cpMode == CPModeGlobal && isZoneOnlyKind(kind) {
			continue
		}

		if cpMode == CPModeZone {
			origin, _ := labels["kuma.io/origin"].(string)
			switch {
			case origin == CPModeZone:
				// explicit zone-origin → keep
			case origin == "" && isGatewayLocalKind(kind):
				// gateway-local kinds may lack origin label on zone CPs → keep
			default:
				continue
			}
		}

		var filename string
		if ns != "" {
			filename = sanitize(kind+"-"+ns+"-"+name) + ".yaml"
		} else {
			filename = sanitize(kind+"-"+name) + ".yaml"
		}

		sub := resource.KindSubfolder(kind)
		dir := filepath.Join(outputDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			ui.Warn(fmt.Sprintf("mkdir %s: %v", dir, err))
			continue
		}
		outPath := filepath.Join(dir, filename)
		if err := os.WriteFile(outPath, []byte(doc+"\n"), 0644); err != nil {
			ui.Warn(fmt.Sprintf("write %s: %v", outPath, err))
			continue
		}
		ui.FileWritten(sub, filename)
		count++
	}
	return count, nil
}


// splitYAMLDocs splits a byte slice on YAML document separators (---).
func splitYAMLDocs(data []byte) []string {
	content := strings.ReplaceAll(string(data), "\r\n", "\n")
	parts := strings.Split(content, "\n---")
	var docs []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		p = strings.TrimPrefix(p, "---")
		p = strings.TrimSpace(p)
		if p != "" {
			docs = append(docs, p)
		}
	}
	return docs
}

// isInsightKind reports whether the resource kind contains "Insight" (e.g. ZoneInsight,
// DataplaneInsight). These are control-plane-managed status objects, not user policies.
func isInsightKind(kind string) bool {
	return strings.Contains(strings.ToLower(kind), "insight")
}

// sanitize replaces characters that are problematic in file names.
func sanitize(s string) string {
	return strings.NewReplacer("/", "-", ":", "-", " ", "-").Replace(s)
}

// PrintCPModeInfo prints the CP mode banner and relevant notices.
// Called from both ExtractViaKubectl and ExtractViaKumactl.
func PrintCPModeInfo(cpMode, zoneName string, zones []string) {
	switch cpMode {
	case CPModeZone:
		ui.KV("CP mode:", fmt.Sprintf("zone (%s)", zoneName))
		ui.Warn("Extracting from a Zone CP — only kuma.io/origin: zone resources will be kept.")
		ui.WarnIndented("For a complete policy set, also run extract against the Global CP.")
		ui.Info("MeshGatewayInstance and MeshGatewayConfig are zone-local and will be extracted here.")
		ui.Info("MeshGateway and route CRDs (MeshHTTPRoute, MeshTCPRoute, MeshGatewayRoute):")
		ui.InfoIndented("- Synced from Global CP with kuma.io/origin: global → skipped (extract from Global CP).")
		ui.InfoIndented("- Created directly on this Zone CP with no origin label → extracted here.")
	case CPModeGlobal:
		ui.KV("CP mode:", "global")
		if len(zones) > 0 {
			ui.KV("Attached zones:", strings.Join(zones, ", "))
		}
		ui.Info("MeshGateway and route CRDs created on the Global CP are extracted here.")
		ui.Info("MeshGatewayInstance and MeshGatewayConfig are zone-local and skipped here.")
		ui.InfoIndented("Run extract against each Zone CP to capture gateway instances.")
	case CPModeStandalone:
		ui.KV("CP mode:", "standalone")
	default:
		ui.KV("CP mode:", "unknown")
		ui.Warn("Could not detect CP mode — extracting all resources.")
	}
}
